### ISSUE TITLE
pychess.py only works if terminal is in My-PyChess directory (Linux)

### ISSUE THREAD

**Issue by SamMatzko** [ankith26/My-PyChess#12]
In the `My-PyChess` directory created from extracting the `zip` file, I tried to run `pychess.py` from a terminal that was not in the `My-PyChess` directory. I got an error:

```
head = pygame.font.Font(FONT, 80)
FileNotFoundError: [Errno 2] No such file or directory: 'res/Asimov.otf'
```

This error was fixed by running the `cd` command to change the terminal to `My-PyChess`. I don't know if this requirement is intended or not, but it's a little inconvenient to have to be in the `My-PyChess` directory to run it. Could you add something that automatically changes to the correct directory when running `pychess.py`, so that it can be run in the terminal no matter which directory that terminal has open?

**Comment by ankith26** [comment]
Hi!
I'm planning a complete rewrite to revive this old project, but sadly that is not coming anytime soon.
But in the mean time you can fix this problem locally with something like
`os.chdir(os.path.dirname(os.path.abspath(__file__)))` in the main file of the program at the top, after an `import os` ofc (untested)

**Comment by SamMatzko** [comment]
Okay! I might make a pull request to fix this.

**Comment by SamMatzko** [comment]
Closing this issue, now that it's solved by my pull request.
