### ISSUE TITLE
game step pace of the computer

### ISSUE THREAD

**Issue by Paralullus** [ankith26/My-PyChess#3]
The game step pace of the computer is a very fast reaction.
Give me the impression of being slow and also simple.
I wish this reaction wait a little,

**Comment by ankith26** [comment]
Hmm, in the coming versions when I implement stronger algorithms, the speed of computer in single player will be reduced

**Comment by Den-W1** [comment]
I have a young grandson that is starting to learn chess.  Having the ability to turn the timer off or change it to a longer time, I feel would be a nice enhancement.

**Comment by ankith26** [comment]
I am seeing this message quite late, you could have opened a new issue to message me. Anyways, I am considering adding the timer in a future release.

**Comment by ankith26** [comment]
V3.2 adds timer, closing this issue.
