### ISSUE TITLE
board size 

### ISSUE THREAD

**Issue by Paralullus** [ankith26/My-PyChess#4]
Dear ankith26,
I want to be able to choose the size of the board soon.
Have I already mentioned how great it is that I can participate in your game programming here, learn pygame and the pictures look good as accompanying circumstances.
have excellent times, cordially
Paralullus

**Comment by ankith26** [comment]
What I actually mean by changing size of the board is resizing the game window... the chess board will remain 8x8 only.

This change should be bought after a few months as I am waiting for the new version of pygame to be released.

**Comment by ankith26** [comment]
V3.2 adds this feature, closing issue.
